Add script error check to Git pre-commit hook
Supports #5.

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -17,46 +17,67 @@
 # File: git/hooks/pre-commit
 # Description: Git pre-commit hook script for the cmake-utilities repository.
 
-function abort()
+function message()
 {
-    exit 1
+    local -r content="$1"
+
+    echo -n "$mnemonic: $content"
+}
+
+function errors_found()
+{
+    echo "error(s) found"
 }
 
 function error()
 {
-    local param_message; declare -r param_message="$1"
+    local -r message="$1"
 
-    ( >&2 echo "$MNEMONIC: $param_message" )
+    ( >&2 echo "$mnemonic: $message" )
 }
 
-function message()
+function abort()
 {
-    local param_content; declare -r param_content="$1"
+    if [[ "$#" -gt 0 ]]; then
+        local -r message="$1"
 
-    echo -n "$MNEMONIC: $param_content"
+        error "$message, aborting"
+    fi
+
+    exit 1
 }
 
 function display_help_text()
 {
     echo "NAME"
-    echo "    $MNEMONIC - Execute the cmake-utilities repository's Git pre-commit hook."
+    echo "    $mnemonic - Ensure filenames are portable, no whitespace errors are"
+    echo "        present, and no script errors are present."
     echo "SYNOPSIS"
-    echo "    $MNEMONIC --help"
-    echo "    $MNEMONIC"
+    echo "    $mnemonic --help"
+    echo "    $mnemonic --version"
+    echo "    $mnemonic"
     echo "OPTIONS"
     echo "    --help"
     echo "        Display this help text."
+    echo "    --version"
+    echo "        Display the version of this script."
     echo "EXAMPLES"
-    echo "    $MNEMONIC --help"
-    echo "    $MNEMONIC"
+    echo "    $mnemonic --help"
+    echo "    $mnemonic --version"
+    echo "    $mnemonic"
+}
+
+function display_version()
+{
+    echo "$mnemonic, version $version"
 }
 
 function ensure_filenames_are_portable()
 {
     message "checking for non-portable (non-ASCII) filenames ... "
 
-    if [[ $( git diff --cached --name-only --diff-filter=A -z $AGAINST | LC_ALL=C tr -d '[ -~]\0' | wc -c ) != 0 ]]; then
-        echo "error(s) found"
+    if [[ $( git -C "$repository" diff --cached --name-only --diff-filter=A -z "$against" | LC_ALL=C tr -d '[ -~]\0' | wc -c ) != 0 ]]; then
+        errors_found
         error "aborting commit due to non-portable (non-ASCII) filename(s)"
         abort
     fi
@@ -68,10 +89,26 @@ function ensure_no_whitespace_errors_are_present()
 {
     message "checking for whitespace errors .................... "
 
-    if ! git diff-index --check --cached $AGAINST -- >/dev/null 2>&1; then
-        echo "error(s) found"
+    if ! git -C "$repository" diff-index --check --cached "$against" -- > "/dev/null"; then
+        errors_found
         error "aborting commit due to whitespace error(s), listed below"
-        git diff-index --check --cached $AGAINST --
+        git -C "$repository" diff-index --check --cached "$against" --
+        abort
+    fi
+
+    echo "none"
+}
+
+function ensure_no_script_errors_are_present()
+{
+    message "checking for script errors ........................ "
+
+    local scripts; mapfile -t scripts < <( git -C "$repository" ls-files | xargs -r -d '\n' -I '{}' find "$repository/{}" -executable ); readonly scripts
+
+    if ! shellcheck "${scripts[@]}" > "/dev/null" 2>&1; then
+        errors_found
+        error "aborting commit due to script error(s), listed below"
+        shellcheck "${scripts[@]}"
         abort
     fi
 
@@ -80,40 +117,44 @@ function ensure_no_whitespace_errors_are_present()
 
 function main()
 {
-    declare -r SCRIPT=$( readlink -f $0 )
-    declare -r REPOSITORY=$( dirname $SCRIPT )/../..
-    declare -r MNEMONIC=$( basename $SCRIPT )
+    local -r script=$( readlink -f "$0" )
+    local -r mnemonic=$( basename "$script" )
+    local -r hooks=$( dirname "$script" )
+    local -r repository=$( readlink -f "$hooks/../.." )
+    local -r version=$( git -C "$repository" describe --always --dirty --broken )
 
-    while [[ $# -gt 0 ]]; do
-        local argument; argument="$1"
-        shift
+    while [[ "$#" -gt 0 ]]; do
+        local argument="$1"; shift
 
-        case $argument in
+        case "$argument" in
             --help)
                 display_help_text
+                exit
+                ;;
+            --version)
+                display_version
                 exit
                 ;;
             --*)
                 ;&
             -*)
-                error "'$argument' is not a supported option, aborting"
-                abort
+                abort "'$argument' is not a supported option"
                 ;;
             *)
-                error "'$argument' is not a valid argument, aborting"
-                abort
+                abort "'$argument' is not a valid argument"
                 ;;
         esac
     done
 
-    if git rev-parse --verify HEAD >/dev/null 2>&1; then
-        declare -r AGAINST=HEAD
+    if git -C "$repository" rev-parse --verify HEAD > "/dev/null" 2>&1; then
+        local -r against=HEAD
     else
-        declare -r AGAINST=$( git hash-object -t tree /dev/null )
+        local -r against=$( git hash-object -t tree "/dev/null" )
     fi
 
     ensure_filenames_are_portable
     ensure_no_whitespace_errors_are_present
+    ensure_no_script_errors_are_present
 }
 
 main "$@"
